name: Tests
on:
    pull_request:
        branches:
            - master
jobs:
    Jest_Tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: borales/actions-yarn@v2.0.0
              with:
                cmd: install
            - uses: ./.github/actions/test
