name: Tests
on:
    pull_request:
        branches:
            - master
jobs:
    Jest Tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: ./.github/actions/test
